# Generated by Django 5.2.8 on 2025-11-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startuphunterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published Time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startuphunterapp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('country', models.CharField(default='Uzbekistan', max_length=30)),
                ('q1', models.TextField()),
                ('q2', models.TextField()),
                ('q3', models.TextField()),
                ('q4', models.TextField()),
                ('q5', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startuphunterapp.problems')),
            ],
        ),
    ]
