# Generated by Django 5.2.8 on 2025-11-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startuphunterapp', '0002_problems_useranswers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnswers',
            new_name='UserProblems',
        ),
        migrations.AlterField(
            model_name='userproblems',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startuphunterapp.categories'),
        ),
        migrations.DeleteModel(
            name='Problems',
        ),
    ]
