# Generated by Django 5.2.8 on 2025-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startuphunterapp', '0003_rename_useranswers_userproblems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproblems',
            old_name='problem',
            new_name='category',
        ),
        migrations.AddField(
            model_name='userproblems',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userproblems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
