# Generated by Django 5.2.8 on 2025-11-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startuphunterapp', '0004_rename_problem_userproblems_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproblems',
            options={'verbose_name': 'UserProblem', 'verbose_name_plural': 'UserProblems'},
        ),
    ]
